/**
 * Generated by scripts/brand-assets.ts — do not edit by hand.
 * Run `npm run brand:assets` after replacing the logotype.
 */
export const WORDMARK = {
  width: 1200,
  height: 112,
  /** Each glyph's box in image pixels, left to right. */
  letters: [
    { x: 0, w: 108 },
    { x: 161, w: 110 },
    { x: 319, w: 116 },
    { x: 483, w: 126 },
    { x: 663, w: 67 },
    { x: 784, w: 110 },
    { x: 947, w: 110 },
    { x: 1111, w: 89 },
  ],
} as const;
