import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

import sharp from "sharp";

/**
 * Derive the loader-sized mark from the studio's master art.
 *
 * The masters are 4000px and 8000px squares with a lot of transparent margin
 * around the artwork. That is right for a source file and wrong for the
 * first thing a visitor downloads, so this trims the margin away and resizes to
 * the largest size the loader can show on a 3x screen. It also repaints the
 * logotype white and measures where each of its letters sits, which is what
 * lets the overture write the name a letter at a time.
 *
 * Re-run whenever the studio replaces the master art:
 *
 *   npm run brand:assets
 */
const ROOT = path.join(process.cwd(), "public");
const OUT = path.join(ROOT, "brand");

/** The house's cocoa, as `globals.css` sets it. */
const COCOA = { r: 0x43, g: 0x31, b: 0x31, alpha: 1 };
const TRANSPARENT = { r: 0, g: 0, b: 0, alpha: 0 };

// The loader shows the mark at ~152px and the wordmark at ~280px, so these are
// roughly 3.5x — enough for any screen, small enough to arrive with the HTML.
const ASSETS = [
  { from: "fav.webp", to: "moon.webp", width: 560, quality: 82 },
] as const;

/** Trimmed of its transparent margin and sized for the loader. */
function prepare(file: string, width: number) {
  return (
    sharp(path.join(ROOT, file))
      // `threshold: 1` trims fully transparent pixels only, so no part of the
      // artwork's own soft edge is eaten.
      .trim({ threshold: 1 })
      .resize({ width, withoutEnlargement: true })
  );
}

function report(name: string, info: sharp.OutputInfo) {
  console.log(
    `brand/${name}  ${info.width}x${info.height}  ${(info.size / 1024).toFixed(1)} kB`,
  );
}

/**
 * The wordmark as drawn: black on transparency, for the lockup on cream.
 *
 * Trimmed and resized to match the white cut below exactly, so one set of
 * letter boxes describes both.
 */
async function inkWordmark() {
  report(
    "wordmark-ink.webp",
    await prepare("logotext.webp", 1200)
      .webp({ quality: 92, effort: 6, alphaQuality: 100 })
      .toFile(path.join(OUT, "wordmark-ink.webp")),
  );
}

/**
 * The wordmark, repainted white, for the lockup on cocoa.
 *
 * The master draws the name in black on transparency, which disappears against
 * the cocoa the overture plays on. Only the colour is replaced: the original
 * alpha is kept as the mask, so every serif and every hairline of the logotype
 * survives exactly as drawn. (Setting the name in a font is not an option — the
 * logotype is a high-contrast serif, and the house's text face is a grotesque.)
 */
async function whiteWordmark() {
  const { data, info } = await prepare("logotext.webp", 1200)
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const mask = await sharp(data, {
    raw: { width: info.width, height: info.height, channels: info.channels },
  })
    .extractChannel("alpha")
    .toBuffer();

  const out = await sharp({
    create: {
      width: info.width,
      height: info.height,
      channels: 3,
      background: "#ffffff",
    },
  })
    .joinChannel(mask, {
      raw: { width: info.width, height: info.height, channels: 1 },
    })
    .webp({ quality: 92, effort: 6, alphaQuality: 100 })
    .toFile(path.join(OUT, "wordmark.webp"));

  report("wordmark.webp", out);
}

/**
 * Where each glyph of the logotype sits, in image pixels.
 *
 * Read off the alpha channel rather than typed out: a column with no ink in it
 * is a gap between letters, and the runs between the gaps are the letters. The
 * loader needs this to write the name one letter at a time while still showing
 * the drawn logotype rather than a font's approximation of it.
 */
async function writeLetterMetrics() {
  const { data, info } = await sharp(path.join(OUT, "wordmark.webp"))
    .ensureAlpha()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const letters: { x: number; w: number }[] = [];
  let start = -1;

  for (let x = 0; x <= info.width; x++) {
    let ink = 0;
    for (let y = 0; y < info.height && x < info.width; y++) {
      ink += data[(y * info.width + x) * info.channels + 3]!;
    }
    // One faint pixel is dust, not a letter.
    const inked = x < info.width && ink > 255;

    if (inked && start < 0) start = x;
    if (!inked && start >= 0) {
      letters.push({ x: start, w: x - start });
      start = -1;
    }
  }

  const source = `/**
 * Generated by scripts/brand-assets.ts — do not edit by hand.
 * Run \`npm run brand:assets\` after replacing the logotype.
 */
export const WORDMARK = {
  width: ${info.width},
  height: ${info.height},
  /** Each glyph's box in image pixels, left to right. */
  letters: [
${letters.map((l) => `    { x: ${l.x}, w: ${l.w} },`).join("\n")}
  ],
} as const;
`;

  await writeFile(path.join(process.cwd(), "src/lib/brand-wordmark.ts"), source);
  console.log(`brand-wordmark.ts  ${letters.length} glyphs`);
}

/**
 * Wrap PNGs in an ICO container.
 *
 * `app/icon.png` covers every browser that reads the markup, but plenty of
 * crawlers and readers still ask for `/favicon.ico` blindly, and a 404 there is
 * a broken link on every page. ICO has allowed PNG-encoded entries since Vista,
 * so this is a header and a directory around the PNGs — cheaper than a
 * dependency that would do exactly the same thing.
 */
function ico(images: { size: number; png: Buffer }[]): Buffer {
  const HEADER = 6;
  const ENTRY = 16;

  const header = Buffer.alloc(HEADER);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // 1 = icon
  header.writeUInt16LE(images.length, 4);

  let offset = HEADER + ENTRY * images.length;
  const entries = images.map(({ size, png }) => {
    const entry = Buffer.alloc(ENTRY);
    entry.writeUInt8(size >= 256 ? 0 : size, 0); // 0 means 256
    entry.writeUInt8(size >= 256 ? 0 : size, 1);
    entry.writeUInt8(0, 2); // palette size: none
    entry.writeUInt8(0, 3); // reserved
    entry.writeUInt16LE(1, 4); // colour planes
    entry.writeUInt16LE(32, 6); // bits per pixel
    entry.writeUInt32LE(png.length, 8);
    entry.writeUInt32LE(offset, 12);
    offset += png.length;
    return entry;
  });

  return Buffer.concat([header, ...entries, ...images.map((i) => i.png)]);
}

/**
 * The mark on a square field.
 *
 * The inset is small for the tab icons: a favicon is drawn at 16px, and the
 * crescent is mostly the space it encloses, so every percent of margin is a
 * percent of an already tiny mark given away. The home-screen icon keeps a real
 * margin — iOS puts it in a rounded square and clips the corners.
 */
async function markOn(
  size: number,
  background: typeof COCOA | typeof TRANSPARENT,
  inset = 0.02,
) {
  const art = await prepare("fav.webp", size)
    .resize({
      width: Math.round(size * (1 - inset * 2)),
      height: Math.round(size * (1 - inset * 2)),
      fit: "inside",
    })
    .toBuffer();

  return sharp({
    create: { width: size, height: size, channels: 4, background },
  })
    .composite([{ input: art, gravity: "center" }])
    .png({ compressionLevel: 9 });
}

/**
 * The tab and home-screen icons, cut from the same mark.
 *
 * The tab icons carry no field of their own: the crescent is drawn on
 * transparency and sits directly on whatever colour the browser's tab strip is,
 * filling as much of the square as the artwork's own proportions allow.
 *
 * `apple-icon.png` is the exception, and not by choice — iOS composites a
 * home-screen icon onto black, so a transparent one would arrive as a black
 * tile. That one keeps the house's cocoa, and a wider margin, because iOS clips
 * it into a rounded square.
 */
async function icons() {
  const files: [string, number, typeof COCOA | typeof TRANSPARENT, number][] = [
    ["src/app/icon.png", 256, TRANSPARENT, 0.02],
    ["src/app/apple-icon.png", 180, COCOA, 0.14],
  ];

  for (const [to, size, background, inset] of files) {
    const info = await (await markOn(size, background, inset)).toFile(
      path.join(process.cwd(), to),
    );
    console.log(
      `${to}  ${info.width}x${info.height}  ${(info.size / 1024).toFixed(1)} kB`,
    );
  }

  const bundle = ico(
    await Promise.all(
      [16, 32, 48].map(async (size) => ({
        size,
        png: await (await markOn(size, TRANSPARENT, 0.02)).toBuffer(),
      })),
    ),
  );
  await writeFile(path.join(process.cwd(), "src/app/favicon.ico"), bundle);
  console.log(`src/app/favicon.ico  16/32/48  ${(bundle.length / 1024).toFixed(1)} kB`);
}

async function main() {
  await mkdir(OUT, { recursive: true });

  for (const asset of ASSETS) {
    report(
      asset.to,
      await prepare(asset.from, asset.width)
        .webp({ quality: asset.quality, effort: 6 })
        .toFile(path.join(OUT, asset.to)),
    );
  }

  await inkWordmark();
  await whiteWordmark();
  await writeLetterMetrics();
  await icons();
}

main().then(() => process.exit(0));
